### ISSUE TITLE
Different port than ST B-L072Z-LRWAN1 guide

### ISSUE THREAD

**Issue by jklimcak** [helium/longfi-arduino#33]
Hello, I've recently purchased an ST B-L072Z-LRWAN1. Followed the guides on [Helium](https://docs.helium.com/use-the-network/devices/development/stmicroelectronics/st-b-l072z-lrwan1/arduino/), and in your [README](https://github.com/helium/longfi-arduino/tree/master/ST-B-L072Z-LRWAN1/longfi-us915). 

I have a problem in the last step. When it says: "_Navigate to (Tools > Port: COM# or /dev/ttyACM# or usbmodem) depending on whether you are on Windows, Mac, or Linux_.", I only see "/dev/cu.Bluetooth-Incoming-Port" in Tools > Port. I'm using a Mac.

Can you please tell me what I'm doing wrong?

**Comment by leroyle** [comment]
Joe, have you commented in the Sensor-dev channel on Discord? Might need a driver, I'm not a Mac-spert. Or try a different cable? Some of those are power only, some have had success when trying different cables.

**Comment by jklimcak** [comment]
Switching cables indeed helped (or in my case, stop using adapters). Thanks
