### ISSUE TITLE
No GPS lock on TTGo TBeam V1.1

### ISSUE THREAD

**Issue by mauricecyril** [helium/longfi-arduino#37]
Hi I'm able got get the Lora radio to connect to hotspots and can see the join requests and acceptance packets in the helium console. However the GPS never gets a lock so I cannot send data to the mappers integration point. The version 1.1 and version 1.0 use the same pins for the GPS module. Has anyone else been able to resolve this issue of no GPS lock?

**Comment by mauricecyril** [comment]
Hi Everyone I was able to resolve it. Turns out my GPS module was not outputting NMEA. I used the following v3 sketch by eriktheV-King to resolve this: https://github.com/eriktheV-king/TTGO_T-beam_GPS-reset

**Comment by pcunning** [comment]
This was very helpful!

I had the same issue and this fixed it.
