### ISSUE TITLE
Example using Heltec V2 and sensors

### ISSUE THREAD

**Issue by NL647** [helium/longfi-arduino#43]
Hello I ran the example for the Heltec V2 and it works fine, I want to deploy some sensors and i want to know if it is possible to provide an example for the Heltec V2 sending data from a sensor like BME680, please?

Thank you in advance for your help.

**Comment by kent-williams** [comment]
Heltec provides an example for a similar sensor [here](https://github.com/HelTecAutomation/Heltec_ESP32/blob/master/examples/Sensor/BMP180basic/BMP180basic.ino). You should be able to find examples with the BME680 elsewhere.
